version: "3.2"
services:
  backend: &backend
    build:
      context: .
      dockerfile: ./.docker/development/Dockerfile
      args:
        RUBY_VERSION: '2.6.3'
        BUNDLER_VERSION: '2.0.2'
        RAILS_VERSION: '6.0.0'
        PG_MAJOR: '11'
        NODE_MAJOR: '11'
        YARN_VERSION: '1.13.0'
    image: rails-app-dev:1.0.0
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - rails_cache:/app/tmp/cache
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
    tty: true
    stdin_open: true
    tmpfs:
      - /tmp
    depends_on:
      - postgres
      - redis

  web:
    <<: *backend
    container_name: web
    command: /bin/bash -c "
      rm -f tmp/pids/server.pid
      && bundle exec rails server -b 0.0.0.0"
    ports:
      - '3000:3000'

  shell:
    <<: *backend
    container_name: shell
    command: /bin/bash
    ports:
      - '3000:3000'

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml

  webpacker:
    <<: *backend
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  redis:
    image: redis:3.2-alpine
    container_name: redis
    volumes:
      - redis:/data
    ports:
      - 6379

  postgres:
    image: postgres:11.1
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    ports:
      - '5432

volumes:
  postgres:
  bundle:
  node_modules:
  rails_cache:
  packs:
  redis:
